name: VPN Password Auto Update

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-vpn:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Tarayıcıyı ve Bağımlılıkları Kur
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Şifreyi Gerçek Tarayıcıyla Al
        run: python update_pass.py

      - name: Pushle
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add password.json
          git commit -m "Otomatik Güncelleme (Playwright): $(date)" || exit 0
          git push
